Repository doctrine/migrations, pull requests merged in 2018-06, with the labels that each got.

#717 bin/ entrypoint refresh
  bin/doctrine-migrations
  bin/doctrine-migrations.php
  phpcs.xml.dist
Labels: BC Break, Improvement

#718 Remove build.xml as it is unused now.
  build.xml
Labels: Improvement

#715 Rewrite documentation for 2.0
  docs/en/reference/building_framework_specific_integration.rst
  docs/en/reference/configuration.rst
  docs/en/reference/custom-configuration.rst
  docs/en/reference/custom-integration.rst
  docs/en/reference/custom_configuration.rst
  docs/en/reference/events.rst
  docs/en/reference/generating-migrations.rst
  docs/en/reference/generating_migrations.rst
  docs/en/reference/input_output_customization.rst
  docs/en/reference/installation.rst
  docs/en/reference/integration.rst
  docs/en/reference/integrations.rst
  docs/en/reference/introduction.rst
  docs/en/reference/managing-migrations.rst
  docs/en/reference/managing_migrations.rst
  docs/en/reference/migration-classes.rst
  docs/en/reference/migration_classes.rst
  docs/en/reference/version-numbers.rst
  docs/en/sidebar.rst
Labels: Documentation

#719 Fix command return type hints so they are consistent and match what S…
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/LatestCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/RollupCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/UpToDateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
Labels: Improvement

#724 Allow migrations in sub namespace to be loaded if the class is in the…
  lib/Doctrine/Migrations/Finder/Finder.php
  tests/Doctrine/Migrations/Tests/Finder/RecursiveRegexFinderTest.php
Labels: Enhancement

#725 Throw only specialized package-only exceptions
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ArrayConnectionConfigurationLoader.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/Exception/InvalidConfiguration.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/Exception/LoaderException.php
  lib/Doctrine/Migrations/Configuration/Exception/FileNotFound.php
  lib/Doctrine/Migrations/Exception/NoTablesFound.php
  lib/Doctrine/Migrations/Exception/RollupFailed.php
  lib/Doctrine/Migrations/Finder/Exception/FinderException.php
  lib/Doctrine/Migrations/Finder/Exception/InvalidDirectory.php
  lib/Doctrine/Migrations/Finder/Exception/NameIsReserved.php
  lib/Doctrine/Migrations/Finder/Finder.php
  lib/Doctrine/Migrations/Generator/DiffGenerator.php
  lib/Doctrine/Migrations/Generator/Exception/GeneratorException.php
  lib/Doctrine/Migrations/Generator/Exception/InvalidTemplateSpecified.php
  lib/Doctrine/Migrations/Generator/Exception/NoChangesDetected.php
  lib/Doctrine/Migrations/Generator/Generator.php
  lib/Doctrine/Migrations/Provider/Exception/NoMappingFound.php
  lib/Doctrine/Migrations/Provider/Exception/ProviderException.php
  lib/Doctrine/Migrations/Provider/OrmSchemaProvider.php
  lib/Doctrine/Migrations/Rollup.php
  lib/Doctrine/Migrations/SchemaDumper.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
  lib/Doctrine/Migrations/Tools/Console/ConnectionLoader.php
  lib/Doctrine/Migrations/Tools/Console/Exception/ConnectionNotSpecified.php
  lib/Doctrine/Migrations/Tools/Console/Exception/ConsoleException.php
  lib/Doctrine/Migrations/Tools/Console/Exception/DirectoryDoesNotExist.php
  lib/Doctrine/Migrations/Tools/Console/Exception/FileTypeNotSupported.php
  lib/Doctrine/Migrations/Tools/Console/Exception/InvalidOptionUsage.php
  lib/Doctrine/Migrations/Tools/Console/Exception/SchemaDumpRequiresNoMigrations.php
  lib/Doctrine/Migrations/Tools/Console/Exception/VersionAlreadyExists.php
  lib/Doctrine/Migrations/Tools/Console/Exception/VersionDoesNotExist.php
  lib/Doctrine/Migrations/Tools/Console/Helper/ConfigurationHelper.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationDirectoryHelper.php
Labels: Improvement

#729 Update README to remove redundent information that exists in the docs.
  README.md
Labels: Improvement

#690 Introduce Doctrine\DBAL\Migrations\AbstractMigration deprecation.
  CHANGELOG.md
  UPGRADE.md
  composer.json
  lib/Doctrine/DBAL/Migrations/AbstractMigration.php
  lib/Doctrine/DBAL/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/AbstractMigration.php
Labels: Improvement

#733 Add phpstan-phpunit to composer.json
  composer.json
  composer.lock
  phpstan.neon
Labels: Improvement

#727 Improve wording
  docs/en/reference/version-numbers.rst
  lib/Doctrine/Migrations/Finder/Exception/NameIsReserved.php
  lib/Doctrine/Migrations/Tools/Console/Exception/SchemaDumpRequiresNoMigrations.php
  tests/Doctrine/Migrations/Tests/Functional/CliTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DumpSchemaCommandTest.php
Labels: Improvement

#735 Use assertSame instead of assertEquals
  tests/Doctrine/Migrations/Tests/AbstractMigrationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractFileConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Finder/FinderTestCase.php
  tests/Doctrine/Migrations/Tests/Finder/GlobFinderTest.php
  tests/Doctrine/Migrations/Tests/Finder/RecursiveRegexFinderTest.php
  tests/Doctrine/Migrations/Tests/Functional/CliTest.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
  tests/Doctrine/Migrations/Tests/Functional/MigrationTableManipulatorTest.php
  tests/Doctrine/Migrations/Tests/Generator/DiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Generator/FileBuilderTest.php
  tests/Doctrine/Migrations/Tests/Generator/GeneratorTest.php
  tests/Doctrine/Migrations/Tests/Generator/SqlGeneratorTest.php
  tests/Doctrine/Migrations/Tests/MigrationPlanCalculatorTest.php
  tests/Doctrine/Migrations/Tests/MigrationRepositoryTest.php
  tests/Doctrine/Migrations/Tests/MigratorTest.php
  tests/Doctrine/Migrations/Tests/OutputWriterTest.php
  tests/Doctrine/Migrations/Tests/ParameterFormatterTest.php
  tests/Doctrine/Migrations/Tests/SchemaDumperTest.php
  tests/Doctrine/Migrations/Tests/StopwatchTest.php
  tests/Doctrine/Migrations/Tests/Tools/BytesFormatterTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/AbstractCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/ExecuteCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Helper/MigrationDirectoryHelperTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Helper/MigrationStatusInfosHelperTest.php
  tests/Doctrine/Migrations/Tests/Tracking/TableDefinitionTest.php
  tests/Doctrine/Migrations/Tests/Version/AliasResolverTest.php
  tests/Doctrine/Migrations/Tests/Version/ExecutionResultTest.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
  tests/Doctrine/Migrations/Tests/Version/VersionTest.php
Labels: Improvement

#739 PHPstan 0.10
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ConnectionConfigurationChainLoader.php
  lib/Doctrine/Migrations/Configuration/Exception/XmlNotValid.php
  lib/Doctrine/Migrations/Configuration/Exception/YamlNotValid.php
  lib/Doctrine/Migrations/Configuration/JsonConfiguration.php
  lib/Doctrine/Migrations/Configuration/XmlConfiguration.php
  lib/Doctrine/Migrations/Configuration/YamlConfiguration.php
  lib/Doctrine/Migrations/Finder/Finder.php
  lib/Doctrine/Migrations/Generator/DiffGenerator.php
  lib/Doctrine/Migrations/MigrationRepository.php
  lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
  lib/Doctrine/Migrations/Tools/Console/Exception/VersionAlreadyExists.php
  lib/Doctrine/Migrations/Tools/Console/Exception/VersionDoesNotExist.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationDirectoryHelper.php
  lib/Doctrine/Migrations/Version/Executor.php
  phpstan.neon
  phpstan.neon.dist
  tests/Doctrine/Migrations/Tests/Configuration/JsonConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/XmlConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/YamlConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/_files/config_malformed.json
  tests/Doctrine/Migrations/Tests/Configuration/_files/config_malformed.xml
  tests/Doctrine/Migrations/Tests/Configuration/_files/config_malformed.yml
Labels: Improvement

#740 Fix: No need to update composer itself twice
  .travis.yml
Labels: Improvement
