Repository doctrine/migrations, pull requests merged in 2018-05, with the labels that each got.

#631 Added info about database host
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationStatusInfosHelper.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Helper/MigrationStatusInfosHelperTest.php
Labels: Enhancement

#634 Fix namespace in bin/doctrine-migrations.php
  bin/doctrine-migrations.php
Labels: Bug

#635 Add functional test for bin/doctrine-migrations.php script.
  composer.json
  composer.lock
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
Labels: Improvement

#638 Add PHPStan strict rules
  composer.json
  composer.lock
  lib/Doctrine/Migrations/Configuration/Configuration.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ConnectionConfigurationLoader.php
  lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
  lib/Doctrine/Migrations/Tools/Console/Helper/ConfigurationHelper.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationDirectoryHelper.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationStatusInfosHelper.php
  phpstan.neon
Labels: Improvement

#641 Extract parameter formatting from Version class and move to Parameter…
  lib/Doctrine/Migrations/ParameterFormatter.php
  lib/Doctrine/Migrations/Version.php
  tests/Doctrine/Migrations/Tests/ParameterFormatterTest.php
Labels: Improvement

#649 Fix the possibility to insert / update NULL values, add Unit-Test
  lib/Doctrine/DBAL/Migrations/Version.php
  tests/Doctrine/DBAL/Migrations/Tests/VersionTest.php
Labels: Bug

#653 Support Symfony 3.4 in Doctrine Migration 2.0 as 3.4 is a LTS release.
  composer.json
  composer.lock
Labels: Improvement

#652 Enhancement: Link to project documentation
  composer.json
Labels: Improvement

#661 Add GitHub issue and PR templates
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Support_Question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#656 Update MigrationsVersion to 1.7.2
  lib/Doctrine/DBAL/Migrations/MigrationsVersion.php
Labels: Bug

#660 Refactor monster Configuration class.
  lib/Doctrine/Migrations/Configuration/Configuration.php
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/MigrationPlanCalculator.php
  lib/Doctrine/Migrations/MigrationRepository.php
  lib/Doctrine/Migrations/MigrationTableCreator.php
  lib/Doctrine/Migrations/ParameterFormatterInterface.php
  lib/Doctrine/Migrations/Version.php
  lib/Doctrine/Migrations/VersionAliasResolver.php
  lib/Doctrine/Migrations/VersionExecutor.php
  lib/Doctrine/Migrations/VersionExecutorInterface.php
  lib/Doctrine/Migrations/VersionFactory.php
  lib/Doctrine/Migrations/VersionInterface.php
  phpcs.xml.dist
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/MigrationPlanCalculatorTest.php
  tests/Doctrine/Migrations/Tests/MigrationTableCreatorTest.php
  tests/Doctrine/Migrations/Tests/VersionAliasResolverTest.php
  tests/Doctrine/Migrations/Tests/VersionFactoryTest.php
Labels: Improvement

#665 Refactor console commands.
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/Configuration/Configuration.php
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/Migration.php
  lib/Doctrine/Migrations/MigrationDiffGenerator.php
  lib/Doctrine/Migrations/MigrationGenerator.php
  lib/Doctrine/Migrations/MigrationRepository.php
  lib/Doctrine/Migrations/MigrationSqlGenerator.php
  lib/Doctrine/Migrations/OutputWriter.php
  lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/LatestCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/UpToDateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
  lib/Doctrine/Migrations/Tools/Console/ConnectionLoader.php
  lib/Doctrine/Migrations/Tools/Console/Helper/ConfigurationHelper.php
  lib/Doctrine/Migrations/Tools/Console/Helper/ConfigurationHelperInterface.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationStatusInfosHelper.php
  lib/Doctrine/Migrations/Version.php
  lib/Doctrine/Migrations/VersionExecutionResult.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractFileConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/Connection/Loader/ConnectionConfigurationLoaderTest.php
  tests/Doctrine/Migrations/Tests/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
  tests/Doctrine/Migrations/Tests/MigrationDiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/MigrationGeneratorTest.php
  tests/Doctrine/Migrations/Tests/MigrationPlanCalculatorTest.php
  tests/Doctrine/Migrations/Tests/MigrationSqlGeneratorTest.php
  tests/Doctrine/Migrations/Tests/MigrationTableCreatorTest.php
  tests/Doctrine/Migrations/Tests/MigrationTest.php
  tests/Doctrine/Migrations/Tests/MigrationTestCase.php
  tests/Doctrine/Migrations/Tests/OutputWriterTest.php
  tests/Doctrine/Migrations/Tests/ParameterFormatterTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/AbstractCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DiffCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/ExecuteCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/GenerateCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrationStatusTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/StatusCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/UpToDateCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/ConnectionLoaderTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Helper/ConfigurationHelperTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Helper/MigrationStatusInfosHelperTest.php
  tests/Doctrine/Migrations/Tests/VersionAliasResolverTest.php
  tests/Doctrine/Migrations/Tests/VersionExecutorTest.php
  tests/Doctrine/Migrations/Tests/VersionFactoryTest.php
  tests/Doctrine/Migrations/Tests/VersionTest.php
Labels: Improvement

#674 Configure column length
  lib/Doctrine/Migrations/Configuration/Configuration.php
  lib/Doctrine/Migrations/MigrationTableCreator.php
  tests/Doctrine/Migrations/Tests/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/MigrationTableCreatorTest.php
Labels: Enhancement

#538 #514 -- Add support for configurable migration column length.
  lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php
Labels: Improvement, Needs Tests

#671 Rename Doctrine\Migrations\Migration to Doctrine\Migrations\Migrator
  UPGRADE.md
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/Migrator.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
  tests/Doctrine/Migrations/Tests/MigrationTest.php
  tests/Doctrine/Migrations/Tests/MigrationTestCase.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
Labels: BC break, Improvement

#673 Show more help text after generating a migration.
  lib/Doctrine/Migrations/MigrationDiffGenerator.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  tests/Doctrine/Migrations/Tests/MigrationDiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DiffCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/GenerateCommandTest.php
Labels: DX, Documentation, Improvement

#666 Fix --write-sql option so it can accept a path to write the sql file to.
  docs/en/reference/managing_migrations.rst
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/ExecuteCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
Labels: Enhancement

#659 Update license to MIT.
  LICENSE
  composer.json
Labels: Improvement

#684 Add shorter console command aliases to improve developer experience.
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/LatestCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/UpToDateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
Labels: DX, Improvement

#680 Fix issue with not being able to configure column_length
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/Configuration/XML/configuration.xsd
  lib/Doctrine/Migrations/Configuration/XmlConfiguration.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractFileConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.json
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.php
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.xml
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.yml
  tests/Doctrine/Migrations/Tests/Configuration/_files/config_migrations_list.php
  tests/Doctrine/Migrations/Tests/Functional/MigrationTableManipulatorTest.php
Labels: Bug

#679 Use DBAL connection defaultTableOptions when creating migrations table
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/MigrationTable.php
  lib/Doctrine/Migrations/MigrationTableUpdater.php
  tests/Doctrine/Migrations/Tests/Functional/MigrationTableManipulatorTest.php
  tests/Doctrine/Migrations/Tests/MigrationTableTest.php
  tests/Doctrine/Migrations/Tests/MigrationTableUpdaterTest.php
Labels: Bug

#686 Remove unused input and output extension points from bin/doctrine-mig…
  bin/doctrine-migrations.php
Labels: Improvement

#683 Implement all or nothing transaction strategy for migrations.
  docs/en/reference/custom_configuration.rst
  docs/en/reference/installation.rst
  docs/en/reference/introduction.rst
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/Configuration/Configuration.php
  lib/Doctrine/Migrations/Configuration/XML/configuration.xsd
  lib/Doctrine/Migrations/Configuration/XmlConfiguration.php
  lib/Doctrine/Migrations/Migrator.php
  lib/Doctrine/Migrations/MigratorConfig.php
  lib/Doctrine/Migrations/Tools/BooleanStringFormatter.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Version.php
  lib/Doctrine/Migrations/VersionExecutor.php
  lib/Doctrine/Migrations/VersionExecutorInterface.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/AbstractFileConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.json
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.php
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.xml
  tests/Doctrine/Migrations/Tests/Configuration/_files/config.yml
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
  tests/Doctrine/Migrations/Tests/MigratorConfigTest.php
  tests/Doctrine/Migrations/Tests/MigratorTest.php
  tests/Doctrine/Migrations/Tests/Stub/Functional/MigrationThrowsError.php
  tests/Doctrine/Migrations/Tests/Tools/BooleanStringFormatterTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/ExecuteCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
  tests/Doctrine/Migrations/Tests/VersionExecutorTest.php
  tests/Doctrine/Migrations/Tests/VersionTest.php
Labels: BC break, Enhancement, WIP

#687 Fix stopwatch so it uses a single symfony stopwatch instance.
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/Stopwatch.php
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
  tests/Doctrine/Migrations/Tests/MigrationTestCase.php
  tests/Doctrine/Migrations/Tests/StopwatchTest.php
  tests/Doctrine/Migrations/Tests/VersionTest.php
Labels: Improvement

#692 Upgrade composer dependencies.
  composer.lock
Labels: Improvement

#691 Upgrade to Box 3 for phar generation.
  .gitignore
  .travis.yml
  box.json
  box.phar
  build-phar.sh
  composer.json
  tests/Doctrine/Migrations/Tests/BoxPharCompileTest.php
Labels: Improvement

#689 Add ability to dump schema and rollup migrations.
  docs/en/reference/building_framework_specific_integration.rst
  docs/en/reference/introduction.rst
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/MigrationRepository.php
  lib/Doctrine/Migrations/Rollup.php
  lib/Doctrine/Migrations/SchemaDumper.php
  lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/RollupCommand.php
  lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php
  tests/Doctrine/Migrations/Tests/Functional/CliTest.php
  tests/Doctrine/Migrations/Tests/MigrationRepositoryTest.php
  tests/Doctrine/Migrations/Tests/RollupTest.php
  tests/Doctrine/Migrations/Tests/SchemaDumperTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DumpSchemaCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/RollupCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/ConsoleRunnerTest.php
Labels: Enhancement

#698 Testing on AppVeyor
  .appveyor.yml
  tests/Doctrine/Migrations/Tests/BoxPharCompileTest.php
  tests/Doctrine/Migrations/Tests/Finder/RecursiveRegexFinderTest.php
  tests/Doctrine/Migrations/Tests/Functional/CliTest.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
Labels: Enhancement

#700 Remove box.phar from git and improve box build process
  .gitignore
  .travis.yml
  box.phar
  build-phar.sh
  download-box.sh
  tests/Doctrine/Migrations/Tests/BoxPharCompileTest.php
Labels: Enhancement

#706 Always store executed_at in UTC and render using date_default_timezone()
  lib/Doctrine/Migrations/Version.php
  tests/Doctrine/Migrations/Tests/VersionTest.php
Labels: Enhancement

#711 Mark classes as internal that nobody should be depending on.
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/Configuration/ArrayConfiguration.php
  lib/Doctrine/Migrations/Configuration/Connection/ConnectionLoaderInterface.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ArrayConnectionConfigurationLoader.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ConnectionConfigurationChainLoader.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ConnectionConfigurationLoader.php
  lib/Doctrine/Migrations/Configuration/Connection/Loader/ConnectionHelperLoader.php
  lib/Doctrine/Migrations/Configuration/JsonConfiguration.php
  lib/Doctrine/Migrations/Configuration/XmlConfiguration.php
  lib/Doctrine/Migrations/Configuration/YamlConfiguration.php
  lib/Doctrine/Migrations/Event/Listeners/AutoCommitListener.php
  lib/Doctrine/Migrations/FileQueryWriter.php
  lib/Doctrine/Migrations/Finder/Finder.php
  lib/Doctrine/Migrations/Finder/GlobFinder.php
  lib/Doctrine/Migrations/Finder/MigrationDeepFinder.php
  lib/Doctrine/Migrations/Finder/RecursiveRegexFinder.php
  lib/Doctrine/Migrations/Generator/DiffGenerator.php
  lib/Doctrine/Migrations/Generator/Generator.php
  lib/Doctrine/Migrations/Migrator.php
  lib/Doctrine/Migrations/MigratorConfiguration.php
  lib/Doctrine/Migrations/OutputWriter.php
  lib/Doctrine/Migrations/Provider/LazySchemaDiffProvider.php
  lib/Doctrine/Migrations/Provider/OrmSchemaProvider.php
  lib/Doctrine/Migrations/Provider/SchemaDiffProvider.php
  lib/Doctrine/Migrations/Provider/SchemaDiffProviderInterface.php
  lib/Doctrine/Migrations/QueryWriter.php
  lib/Doctrine/Migrations/Rollup.php
  lib/Doctrine/Migrations/SchemaDumper.php
  lib/Doctrine/Migrations/Stopwatch.php
  lib/Doctrine/Migrations/Tools/BooleanStringFormatter.php
  lib/Doctrine/Migrations/Tools/BytesFormatter.php
  lib/Doctrine/Migrations/Tools/Console/ConnectionLoader.php
  lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationDirectoryHelper.php
  lib/Doctrine/Migrations/Tools/Console/Helper/MigrationStatusInfosHelper.php
  lib/Doctrine/Migrations/Tracking/TableDefinition.php
  lib/Doctrine/Migrations/Tracking/TableStatus.php
  lib/Doctrine/Migrations/Tracking/TableUpdater.php
  lib/Doctrine/Migrations/Version/Direction.php
  lib/Doctrine/Migrations/Version/State.php
  lib/Doctrine/Migrations/Version/Version.php
  lib/Doctrine/Migrations/Version/VersionInterface.php
Labels: Enhancement
