Repository doctrine/migrations, pull requests merged in 2019-03, with the labels that each got.

#797 Update to doctrine/coding-standard 6.0
  composer.json
  composer.lock
  lib/Doctrine/Migrations/AbstractMigration.php
  lib/Doctrine/Migrations/Configuration/AbstractFileConfiguration.php
  lib/Doctrine/Migrations/Finder/Finder.php
  lib/Doctrine/Migrations/Migrator.php
  lib/Doctrine/Migrations/Provider/LazySchemaDiffProvider.php
  lib/Doctrine/Migrations/Tools/BooleanStringFormatter.php
  lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php
  lib/Doctrine/Migrations/Tools/Console/Helper/ConfigurationHelper.php
  lib/Doctrine/Migrations/Version/AliasResolver.php
  lib/Doctrine/Migrations/Version/Version.php
  tests/Doctrine/Migrations/Tests/MigrationPlanCalculatorTest.php
  tests/Doctrine/Migrations/Tests/MigrationTestCase.php
  tests/Doctrine/Migrations/Tests/Stub/VersionDummyDescription.php
Labels: Improvement

#799 handle unregistered migrations in up-to-date check
  lib/Doctrine/Migrations/Tools/Console/Command/UpToDateCommand.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/UpToDateCommandTest.php
Labels: Enhancement

#803 allow "float" in formatBytes to work on 32-bit computers
  lib/Doctrine/Migrations/Tools/BytesFormatter.php
Labels: Bug

#804 removed internal from factory
  lib/Doctrine/Migrations/Version/Factory.php
Labels: Improvement
