Repository doctrine/migrations, pull requests merged in 2019-04, with the labels that each got.

#812 Fix typo
  docs/en/reference/configuration.rst
Labels: Documentation

#808 Handle deleted migration classes #795
  lib/Doctrine/Migrations/MigrationRepository.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
  tests/Doctrine/Migrations/Tests/MigrationRepositoryTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrationVersionTest.php
Labels: Enhancement

#813 Make migration class final by default in custom_template tests
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/_files/migration.tpl
Labels: Tests

#809 Fix for referencing tables created during a dry run
  lib/Doctrine/Migrations/Migrator.php
  lib/Doctrine/Migrations/MigratorConfiguration.php
  lib/Doctrine/Migrations/Version/ExecutionResult.php
  lib/Doctrine/Migrations/Version/Executor.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
  tests/Doctrine/Migrations/Tests/Stub/Functional/DryRun/DryRun1.php
  tests/Doctrine/Migrations/Tests/Stub/Functional/DryRun/DryRun2.php
  tests/Doctrine/Migrations/Tests/Version/ExecutionResultTest.php
Labels: Bug

#815 Fixed event that was firing twice when it should only fire once.
  lib/Doctrine/Migrations/Migrator.php
  tests/Doctrine/Migrations/Tests/Functional/FunctionalTest.php
Labels: Bug
