Repository doctrine/migrations, pull requests merged in 2019-12, with the labels that each got.

#882 Mark as executed only if all queries pass
  lib/Doctrine/Migrations/Version/DbalExecutor.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Bug

#887 [2.2.x] Allow to throw Exception in Migrations
  lib/Doctrine/Migrations/AbstractMigration.php
Labels: Bug

#888 Use executeUpdate instead of executeQuery for write operation
  lib/Doctrine/Migrations/Version/Executor.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Improvement

#892 Version is not a number but a FQCN
  lib/Doctrine/Migrations/Finder/Exception/NameIsReserved.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/LatestCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
Labels: Documentation, Enhancement

#890 Initialize schema table even on reset
  lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorage.php
  tests/Doctrine/Migrations/Tests/Metadata/Storage/TableMetadataStorageTest.php
Labels: Bug

#889 Executed at must be an integer
  lib/Doctrine/Migrations/Metadata/ExecutedMigration.php
  lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorage.php
  lib/Doctrine/Migrations/Version/DbalExecutor.php
  tests/Doctrine/Migrations/Tests/Metadata/ExecutedMigrationSetTest.php
  tests/Doctrine/Migrations/Tests/Metadata/Storage/TableMetadataStorageTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/StatusCommandTest.php
Labels: Bug

#894 Use interfaces where possible as service names
  lib/Doctrine/Migrations/DependencyFactory.php
Labels: Bug
