Repository doctrine/migrations, pull requests merged in 2019-07, with the labels that each got.

#839 Lazy console commands
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/LatestCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/RollupCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/UpToDateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
Labels: Enhancement

#842 Fixed docs for required params in the configuration
  docs/en/reference/configuration.rst
Labels: Documentation

#843 Handle missing jdorn/sql-formatter dependency in dump-schema command
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
Labels: Bug

#830 [DOCS] Added use statement for `Events`
  docs/en/reference/events.rst
Labels: Documentation

#841 Fixed default name in the documentation: Doctrine Database Migrations
  docs/en/reference/configuration.rst
Labels: Documentation
