Repository doctrine/migrations, pull requests merged in 2019-01, with the labels that each got.

#773 Change the column length of the version column to default to 14
  lib/Doctrine/Migrations/Configuration/Configuration.php
  tests/Doctrine/Migrations/Tests/ConfigurationTest.php
Labels: Improvement

#775 Use DateTimeImmutable instead of DateTime.
  lib/Doctrine/Migrations/Configuration/Configuration.php
  lib/Doctrine/Migrations/FileQueryWriter.php
Labels: Enhancement, Improvement

#777 Use UTC timezone consistently when creating dates.
  lib/Doctrine/Migrations/Configuration/Configuration.php
Labels: Improvement

#779 CI: Use Ubuntu 16.04
  .travis.yml
Labels: Improvement

#783 Small fixes for docs
  docs/en/reference/configuration.rst
  docs/en/reference/introduction.rst
Labels: Documentation
