Repository doctrine/migrations, pull requests merged in 2020-11, with the labels that each got.

#1071 Revert "Merge pull request #888 from goetas/update-query"
  lib/Doctrine/Migrations/Version/Executor.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Bug

#1081 Address master branch rename in the docs
  .doctrine-project.json
  README.md
Labels: Documentation

#1079 A whole slew of changes for 3.0.x! See the summary.
  .github/workflows/continuous-integration.yml
  composer.json
  download-box.sh
  lib/Doctrine/Migrations/Configuration/Configuration.php
  tests/Doctrine/Migrations/Tests/Configuration/ConfigurationTest.php
  tests/Doctrine/Migrations/Tests/Generator/ClassNameGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Generator/DiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/RollupTest.php
  tests/Doctrine/Migrations/Tests/SchemaDumperTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/StatusCommandTest.php
Labels: Enhancement

#1076 Update configuration.rst to include the `organize_migrations` setting.
  docs/en/reference/configuration.rst
Labels: Documentation

#1043 Set dependencyFactory before configure is called in DoctrineCommand
  lib/Doctrine/Migrations/Tools/Console/Command/DoctrineCommand.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DoctrineCommandTest.php
Labels: Bug
