Repository doctrine/migrations, pull requests merged in 2020-06, with the labels that each got.

#984 Address deprecations from doctrine/persistence
  composer.json
  composer.lock
  tests/Doctrine/Migrations/Tests/Configuration/EntityManager/_files/em-loader.php
  tests/Doctrine/Migrations/Tests/Configuration/EntityManager/_files/migrations-em.php
  tests/Doctrine/Migrations/Tests/Tools/Console/config/cli-config.php
Labels: Tests

#992 Use CodeCov instead of Scrutinizer
  .scrutinizer.yml
  .travis.yml
  README.md
Labels: CI

#988 Re-enable alpha1 meaningful message when "latest" already reached.
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
Labels: Enhancement

#1007 fix typo
  docs/en/reference/custom-configuration.rst
Labels: Documentation

#981 Add "from-empty-schema" option for "diff" command
  docs/en/reference/generating-migrations.rst
  lib/Doctrine/Migrations/Generator/DiffGenerator.php
  lib/Doctrine/Migrations/Provider/EmptySchemaProvider.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  tests/Doctrine/Migrations/Tests/Functional/CliTest.php
  tests/Doctrine/Migrations/Tests/Generator/DiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Provider/EmptySchemaProviderTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DiffCommandTest.php
Labels: Enhancement

#1006 Document table metadata configs are optional
  UPGRADE.md
Labels: Documentation

#1015 Migrate returns 0 as exit codes for empty plans as in 2.x
  UPGRADE.md
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
Labels: Bug

#1018 Explain that the name config property has been removed
  UPGRADE.md
Labels: Documentation

#1010 #998: Show query and time information when using --query-time
  lib/Doctrine/Migrations/Version/DbalExecutor.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Enhancement

#1027 Issue1024
  docs/en/reference/configuration.rst
Labels: Documentation
