Repository doctrine/migrations, pull requests merged in 2020-04, with the labels that each got.

#954 Make compared tables order idempotent
  lib/Doctrine/Migrations/Provider/OrmSchemaProvider.php
  tests/Doctrine/Migrations/Tests/Provider/A.php
  tests/Doctrine/Migrations/Tests/Provider/B.php
  tests/Doctrine/Migrations/Tests/Provider/C.php
  tests/Doctrine/Migrations/Tests/Provider/ClassMetadataFactory.php
  tests/Doctrine/Migrations/Tests/Provider/OrmSchemaProviderTest.php
  tests/Doctrine/Migrations/Tests/Provider/_files/Doctrine.Migrations.Tests.Provider.A.dcm.xml
  tests/Doctrine/Migrations/Tests/Provider/_files/Doctrine.Migrations.Tests.Provider.B.dcm.xml
  tests/Doctrine/Migrations/Tests/Provider/_files/Doctrine.Migrations.Tests.Provider.C.dcm.xml
Labels: Enhancement

#960 Reduce primary key max length to 191 chars
  lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorageConfiguration.php
  tests/Doctrine/Migrations/Tests/Configuration/Migration/LoaderTest.php
  tests/Doctrine/Migrations/Tests/Metadata/Storage/TableMetadataStorageConfigurationTest.php
Labels: Bug

#964 Fix typos
  docs/en/reference/migration-classes.rst
  lib/Doctrine/Migrations/MigrationRepository.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
Labels: Documentation

#965 Add command to display current version
  lib/Doctrine/Migrations/Tools/Console/Command/CurrentCommand.php
  lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/CurrentCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/ConsoleRunnerTest.php
Labels: Enhancement

#971 Migrate to Doctrine's fork of jdorn/sql-formatter
  composer.json
  composer.lock
  docs/en/reference/generating-migrations.rst
  lib/Doctrine/Migrations/Generator/SqlGenerator.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
  tests/Doctrine/Migrations/Tests/Generator/SqlGeneratorTest.php
Labels: Improvement
