Repository doctrine/migrations, pull requests merged in 2021-11, with the labels that each got.

#1206 Reuse workflows and setup Psalm
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
Labels: CI

#1211 Allow Symfony 6
  .github/workflows/continuous-integration.yml
  composer.json
  phpunit.xml.dist
Labels: Improvement

#1210 Look harder for a native connection
  lib/Doctrine/Migrations/Tools/TransactionHelper.php
  phpstan-common.neon.dist
  tests/Doctrine/Migrations/Tests/Event/Listeners/AutoCommitListenerTest.php
  tests/Doctrine/Migrations/Tests/MigratorTest.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Bug

#1215 Fix PhpFile FQCN in Advanced Configuration example
  docs/en/reference/configuration.rst
Labels: Documentation
