Repository doctrine/migrations, pull requests merged in 2023-10, with the labels that each got.

#1305 Deprecate using `--all-or-nothing` with values
  UPGRADE.md
  lib/Doctrine/Migrations/Tools/Console/ConsoleInputMigratorConfigurationFactory.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/MigrateCommandTest.php
Labels: Deprecation

#1333 build: Update Box
  .github/workflows/continuous-integration.yml
  download-box.sh
Labels: CI

#1364 Use github actions format for BC check
  .github/workflows/bc-check.yml
Labels: CI

#1363 Compatibility with ORM 3 and DBAL 4
  .github/workflows/continuous-integration.yml
  composer.json
  lib/Doctrine/Migrations/DependencyFactory.php
  lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorage.php
  lib/Doctrine/Migrations/SchemaDumper.php
  phpstan.neon.dist
  tests/Doctrine/Migrations/Tests/Configuration/Connection/ConnectionLoaderTest.php
  tests/Doctrine/Migrations/Tests/Configuration/EntityManager/EntityManagerTest.php
  tests/Doctrine/Migrations/Tests/Event/Listeners/AutoCommitListenerTest.php
  tests/Doctrine/Migrations/Tests/Generator/DiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Generator/SqlGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Metadata/Storage/TableMetadataStorageTest.php
  tests/Doctrine/Migrations/Tests/MigratorTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/ConsoleRunnerTest.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Improvement

#1370 Remove overrides of deprecated static Command properties
  lib/Doctrine/Migrations/Tools/Console/Command/CurrentCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/DumpSchemaCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/GenerateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/LatestCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/ListCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/RollupCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/SyncMetadataCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/UpToDateCommand.php
  lib/Doctrine/Migrations/Tools/Console/Command/VersionCommand.php
Labels: BC Break
