Repository doctrine/migrations, pull requests merged in 2023-08, with the labels that each got.

#1350 Fix PHPStan errors after PHPUnit update
  composer.json
  tests/Doctrine/Migrations/Tests/AbstractMigrationTest.php
  tests/Doctrine/Migrations/Tests/Event/Listeners/AutoCommitListenerTest.php
  tests/Doctrine/Migrations/Tests/Generator/DiffGeneratorTest.php
  tests/Doctrine/Migrations/Tests/Generator/GeneratorTest.php
  tests/Doctrine/Migrations/Tests/MigratorTest.php
  tests/Doctrine/Migrations/Tests/SchemaDumperTest.php
  tests/Doctrine/Migrations/Tests/Tools/Console/Command/DiffCommandTest.php
  tests/Doctrine/Migrations/Tests/Tools/TransactionHelperTest.php
  tests/Doctrine/Migrations/Tests/Version/ExecutorTest.php
Labels: Static Analysis

#1354 Ditch action in favor of running tool directly
  .github/workflows/bc-check.yml
Labels: CI

#1356 Remove docs from the archives
  .gitattributes
Labels: Improvement
