Repository doctrine/migrations, pull requests merged in 2024-03, with the labels that each got.

#1404 Adjust PHPStan settings for ORM 3 and DBAL 4
  .github/workflows/static-analysis.yml
  phpstan.neon.dist
Labels: CI, Static Analysis

#1405 Bump CI workflows
  .github/workflows/bc-check.yml
  .github/workflows/coding-standards.yml
  .github/workflows/composer-lint.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
Labels: CI

#1408 fix: Allow enum param types: ArrayParameterType and ParameterType
  lib/Doctrine/Migrations/InlineParameterFormatter.php
  tests/Doctrine/Migrations/Tests/InlineParameterFormatterTest.php
Labels: Bug

#1411 Simplify InlineParameterFormatterTest
  composer.json
  tests/InlineParameterFormatterTest.php
Labels: Tests

#1386 Remove unused paramaters from DiffCommand and VersionCommand
  src/Tools/Console/Command/DiffCommand.php
  src/Tools/Console/Command/VersionCommand.php
Labels: Improvement

#1409 Raise PHPStan level to 8
  phpstan.neon.dist
  src/DependencyFactory.php
  src/Tools/Console/Command/DoctrineCommand.php
Labels: Static Analysis

#1412 Remove unused variable $time
  src/DbalMigrator.php
Labels: Improvement
