Repository doctrine/migrations, pull requests merged in 2024-06, with the labels that each got.

#1432 Throw an exception if addSql is used in post methods
  src/AbstractMigration.php
  src/Exception/FrozenMigration.php
  src/Version/DbalExecutor.php
  tests/AbstractMigrationTest.php
Labels: Enhancement

#1437 PHPStan: Remove obsolete rule
  phpstan.neon.dist
Labels: Static Analysis

#1436 Reuse the SqlFormatter instance
  src/Generator/SqlGenerator.php
Labels: Improvement

#1438 Prepare the 3.8.0 release
  .doctrine-project.json
Labels: Documentation
