Repository doctrine/migrations, pull requests merged in 2024-08, with the labels that each got.

#1446 Add native type declarations for Psr\Log\LoggerInterface::log()
  composer.json
  src/Tools/Console/ConsoleLogger.php
  tests/Metadata/Storage/DebugLogger.php
  tests/TestLogger.php
Labels: BC Break

#1450 Remove test logger implementations
  composer.json
  phpcs.xml.dist
  tests/AbstractMigrationTest.php
  tests/LogUtil.php
  tests/Metadata/Storage/DebugLogger.php
  tests/Metadata/Storage/TableMetadataStorageTest.php
  tests/MigrationTestCase.php
  tests/MigratorTest.php
  tests/Tools/Console/Command/MigrationVersionTest.php
  tests/Version/ExecutorTest.php
Labels: Tests

#1452 Allow psr/log 1 again
  composer.json
Labels: Improvement

#1453 Assert there is no failure
  src/Generator/Generator.php
Labels: Static Analysis

#1454 Be consistent with how we deal with preg_match's return type
  src/Generator/Generator.php
Labels: Static Analysis

#1444 GH-1443: Fix default option when `--all-or-nothing` option is used as intended
  docs/en/reference/configuration.rst
  src/Tools/Console/Command/MigrateCommand.php
  src/Tools/Console/ConsoleInputMigratorConfigurationFactory.php
  src/Tools/Console/InvalidAllOrNothingConfiguration.php
  tests/Configuration/ConfigurationTest.php
  tests/Tools/Console/Command/MigrateCommandTest.php
Labels: Bug
